/* eslint-disable */
/* auto-generated by NAPI-RS */

export function version(): string
export function healthCheck(): string

export interface GraphOptions {
  homeDir?: string
  sources?: string[]
  since?: string
  until?: string
  year?: string
  threads?: number
}

export interface TokenBreakdown {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reasoning: number
}

export interface DailyTotals {
  tokens: number
  cost: number
  messages: number
}

export interface SourceContribution {
  source: string
  modelId: string
  providerId: string
  tokens: TokenBreakdown
  cost: number
  messages: number
}

export interface DailyContribution {
  date: string
  totals: DailyTotals
  intensity: number
  tokenBreakdown: TokenBreakdown
  sources: SourceContribution[]
}

export interface YearSummary {
  year: string
  totalTokens: number
  totalCost: number
  rangeStart: string
  rangeEnd: string
}

export interface DataSummary {
  totalTokens: number
  totalCost: number
  totalDays: number
  activeDays: number
  averagePerDay: number
  maxCostInSingleDay: number
  sources: string[]
  models: string[]
}

export interface GraphMeta {
  generatedAt: string
  version: string
  dateRangeStart: string
  dateRangeEnd: string
  processingTimeMs: number
}

export interface GraphResult {
  meta: GraphMeta
  summary: DataSummary
  years: YearSummary[]
  contributions: DailyContribution[]
}

export function generateGraph(options: GraphOptions): GraphResult

export interface ScanStats {
  opencodeFiles: number
  claudeFiles: number
  codexFiles: number
  geminiFiles: number
  totalFiles: number
}

export function scanSessions(homeDir?: string, sources?: string[]): ScanStats

// Pricing-aware APIs

export interface ModelPricing {
  inputCostPerToken: number
  outputCostPerToken: number
  cacheReadInputTokenCost?: number
  cacheCreationInputTokenCost?: number
}

export interface PricingEntry {
  modelId: string
  pricing: ModelPricing
}

export interface ReportOptions {
  homeDir?: string
  sources?: string[]
  pricing: PricingEntry[]
  since?: string
  until?: string
  year?: string
}

export interface ModelUsage {
  source: string
  model: string
  provider: string
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reasoning: number
  messageCount: number
  cost: number
}

export interface ModelReport {
  entries: ModelUsage[]
  totalInput: number
  totalOutput: number
  totalCacheRead: number
  totalCacheWrite: number
  totalMessages: number
  totalCost: number
  processingTimeMs: number
}

export interface MonthlyUsage {
  month: string
  models: string[]
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  messageCount: number
  cost: number
}

export interface MonthlyReport {
  entries: MonthlyUsage[]
  totalCost: number
  processingTimeMs: number
}

export function getModelReport(options: ReportOptions): ModelReport
export function getMonthlyReport(options: ReportOptions): MonthlyReport
export function generateGraphWithPricing(options: ReportOptions): GraphResult
